version: '3.8'

services:
  sheet-viewer:
    build: .
    container_name: sheet-viewer-app
    restart: unless-stopped
    ports:
      # Changed host port to 8081 to avoid conflict
      - "8081:80"
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true