# Étape 1 : Construire l'application
FROM node:18-alpine AS builder
WORKDIR /app

# Copier les fichiers de définition de projet et installer les dépendances
COPY package.json package-lock.json* ./
RUN npm install

# Copier le reste du code source
COPY . .

# Construire l'application pour la production
RUN npm run build

# Étape 2 : Servir l'application construite
FROM node:18-alpine
WORKDIR /app

# Installer 'serve' pour servir les fichiers statiques
RUN npm install -g serve

# Copier uniquement les fichiers construits de l'étape précédente
COPY --from=builder /app/dist .

# Exposer le port sur lequel 'serve' s'exécutera
EXPOSE 3000

# Commande pour démarrer le serveur en mode SPA
CMD ["serve", "-s", "."]
